LIB_NAME			:= histgram
WITHOUT_UNITTEST	?= NO

OPT_WITHOUT_UNITTEST	= -Dwithout-unittest=$(WITHOUT_UNITTEST)

ADDITIONAL_CMAKE_OPTION		= $(OPT_WITHOUT_UNITTEST)
ADDITIONAL_CMD				=

include src/lubee/common.make
