LIB_NAME			:= histgram
WITHOUT_UNITTEST	?= NO
MAKE_COMPILECOMMANDS_LINK := YES

OPT_WITHOUT_UNITTEST	= -Dwithout-unittest=$(WITHOUT_UNITTEST)

ADDITIONAL_CMAKE_OPTION		= $(OPT_WITHOUT_UNITTEST)
ADDITIONAL_CMD				=

include lubee/common.make
